#ifndef TIMEOUT_UTILS_H
#define TIMEOUT_UTILS_H

#include <windows.h>

/* support printing in color */
typedef enum {

	FCOLOR_BLACK       = 0,
	FCOLOR_DARKBLUE    = FOREGROUND_BLUE,
	FCOLOR_DARKGREEN   = FOREGROUND_GREEN,
	FCOLOR_DARKCYAN    = FOREGROUND_GREEN | FOREGROUND_BLUE,
	FCOLOR_DARKRED     = FOREGROUND_RED,
	FCOLOR_DARKMAGENTA = FOREGROUND_RED | FOREGROUND_BLUE,
	FCOLOR_DARKYELLOW  = FOREGROUND_RED | FOREGROUND_GREEN,
	FCOLOR_DARKGRAY    = FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE,
	FCOLOR_GRAY        = FOREGROUND_INTENSITY,
	FCOLOR_BLUE        = FOREGROUND_INTENSITY | FOREGROUND_BLUE,
	FCOLOR_GREEN       = FOREGROUND_INTENSITY | FOREGROUND_GREEN,
	FCOLOR_CYAN        = FOREGROUND_INTENSITY | FOREGROUND_GREEN | FOREGROUND_BLUE,
	FCOLOR_RED         = FOREGROUND_INTENSITY | FOREGROUND_RED,
	FCOLOR_MAGENTA     = FOREGROUND_INTENSITY | FOREGROUND_RED | FOREGROUND_BLUE,
	FCOLOR_YELLOW      = FOREGROUND_INTENSITY | FOREGROUND_RED | FOREGROUND_GREEN,
	FCOLOR_WHITE       = FOREGROUND_INTENSITY | FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE,
	FCOLOR_NULL        = 0xFFFF,

	BCOLOR_BLACK       = 0,
	BCOLOR_DARKBLUE    = BACKGROUND_BLUE,
	BCOLOR_DARKGREEN   = BACKGROUND_GREEN,
	BCOLOR_DARKCYAN    = BACKGROUND_GREEN | BACKGROUND_BLUE,
	BCOLOR_DARKRED     = BACKGROUND_RED,
	BCOLOR_DARKMAGENTA = BACKGROUND_RED | BACKGROUND_BLUE,
	BCOLOR_DARKYELLOW  = BACKGROUND_RED | BACKGROUND_GREEN,
	BCOLOR_DARKGRAY    = BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_BLUE,
	BCOLOR_GRAY        = BACKGROUND_INTENSITY,
	BCOLOR_BLUE        = BACKGROUND_INTENSITY | BACKGROUND_BLUE,
	BCOLOR_GREEN       = BACKGROUND_INTENSITY | BACKGROUND_GREEN,
	BCOLOR_CYAN        = BACKGROUND_INTENSITY | BACKGROUND_GREEN | BACKGROUND_BLUE,
	BCOLOR_RED         = BACKGROUND_INTENSITY | BACKGROUND_RED,
	BCOLOR_MAGENTA     = BACKGROUND_INTENSITY | BACKGROUND_RED | BACKGROUND_BLUE,
	BCOLOR_YELLOW      = BACKGROUND_INTENSITY | BACKGROUND_RED | BACKGROUND_GREEN,
	BCOLOR_WHITE       = BACKGROUND_INTENSITY | BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_BLUE,
	BCOLOR_NULL        = 0xFFFF

} ConsoleColor;

void printfColor(ConsoleColor foreground, ConsoleColor background, const char *format, ...);
void saveConsoleAttributes(WORD *attributes);
void loadConsoleAttributes(WORD attributes);

#define FTYPE double

FTYPE roundLocal(FTYPE x);

#endif
